---
repos:

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint", "-s"]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [--line-length=88]
        files: '(\.py)$'
        language_version: python3

  #  - repo: https://github.com/PyCQA/flake8
  #    rev: 3.9.0
  #    hooks:
  #      - id: flake8
  #        # Harmonizing flake8 and black
  #        args: [--max-line-length=88]
  #        files: '(\.py)$'

  - repo: https://github.com/igorshubovych/markdownlint-cli.git
    rev: v0.38.0
    hooks:
      - id: markdownlint

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: forbid-binary
        exclude: ^(lib|conf/servers)/.*$
      - id: git-check     # Configure in .gitattributes
      - id: markdownlint  # Configure in .mdlrc
      - id: require-ascii
      - id: script-must-have-extension
      - id: shellcheck
      - id: shfmt

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: sort-simple-yaml
      - id: trailing-whitespace
