language: generic
sudo: required
group: deprecated-2017Q4
env:
  global:
  - |
    PATH=${PATH//:\.\/node_modules\/\.bin/} # Workaround for Travis issue #4862
    CWD="$TRAVIS_BUILD_DIR"
  matrix:
  - TEST_ARGS="-x -f /etc/hosts -h"
  - TEST_ARGS="-v -t -M4.0.0.1010 -d 1000 -p EURUSD -m 1 -y 2016 -s 10 -b DS -D5 -e TestFXTHeader"
  - TEST_ARGS="-v -t -M4.0.0.1010 -d 1000 -p EURUSD -m 1 -y 2017 -s 10 -b DS -D5 -e TestHSTHeader"
  - TEST_ARGS="-v -t -M4.0.0.1010 -d 1000 -p EURUSD -m 1 -y 2016 -s 10 -b DS -D5 -e TestTimeframes -P M15"
  - TEST_ARGS="-v -t -M4.0.0.1010 -d 1000 -p EURUSD -m 1 -y 2017 -s 10 -b DS -D5 -e TestTimeframes -P M30"
  - TEST_ARGS="-v -t -M4.0.0.1010 -d 1000 -p EURUSD -m 1 -y 2016 -s 10 -b DS -D5 -e TestBands -P M15"
  - TEST_ARGS="-v -t -M4.0.0.1010 -d 1000 -p EURUSD -m 1 -y 2017 -s 10 -b DS -D5 -e TestBands -P M30"
  - TEST_ARGS="-v -t -M4.0.0.1010 -d 1000 -p EURUSD -m 1 -y 2016 -s 10 -b DS -D5 -e TestModellingQuality -P M1"
  - TEST_ARGS="-v -t -M4.0.0.1010 -d 1000 -p EURUSD -m 1 -y 2017 -s 10 -b DS -D5 -e TestModellingQuality -P M30"
  - TEST_ARGS="-v -t -M4.0.0.1010 -d 2000 -p EURUSD -m 1 -y 2016 -s 20 -b DS -D4 -e TestLotstep -P M1"
# - TEST_ARGS="-v -t -M4.0.0.1010 -d 2000 -p EURUSD -m 1 -y 2017 -s 20 -b DS -D5 -e TestLotstep -P M5" # @fixme: Error: Expected lot step for 5 digits: 0.01, found: 0.1
# Tests which suppose to be working in older versions only.
# - TEST_ARGS="-v -t -d 1000 -p EURUSD -m 1-12 -y 2015 -s 10 -b DS -D5 -e TestFXTHeader -M4.0.0.971 -R"
# - TEST_ARGS="-v -t -d 1000 -p EURUSD -m 1-12 -y 2015 -s 10 -b DS -D5 -e TestFXTHeader -M4.0.0.988 -R"
# - TEST_ARGS="-v -t -d 1000 -p EURUSD -m 1-12 -y 2015 -s 10 -b DS -D5 -e TestHSTHeader -M4.0.0.988 -R"
# - TEST_ARGS="-v -t -d 1000 -p EURUSD -m 1-12 -y 2015 -s 10 -b DS -D5 -e TestHSTHeader -R -M4.0.0.988"
# Tests which does not work.
# - TEST_ARGS="-v -t -M4x -d 1000 -p EURUSD -m 1-12 -y 2015 -s 10 -b DS -D5 -e TestTimeframes -P M1"
# - TEST_ARGS="-v -t -M4x -d 1000 -p EURUSD -m 1-12 -y 2015 -s 10 -b DS -D5 -e TestBands -P M1"
matrix:
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
    on_start: never
before_install:
- ulimit -a && free -m
install:
- sudo "$CWD"/scripts/provision.sh
before_script:
script:
- ruby -wc "$CWD"/Vagrantfile
- bash "$CWD"/scripts/run_backtest.sh $TEST_ARGS
after_script:
- echo AFTER SCRIPT
after_success:
- echo SUCCESS!
after_failure:
- bash -x "$CWD"/scripts/.vars.inc.sh
- tree ~/.wine/drive_c/Program*
before_cache:
- set +e
- test -d ~/.wine/drive_c && find ~/.wine/drive_c -type l -delete
cache:
  apt: true
  pip: true
before_deploy:
- MT_VER=$("$CWD"/scripts/eval.sh filever terminal.exe)
- bash "$CWD"/scripts/eval.sh '[ "$TERMINAL_DIR" ] && clean_bt && clean_files && clean_ea' || exit 0
- cd "$HOME/.wine/drive_c/Program Files (x86)"/
- zip -vr "${HOME}/mt-${MT_VER}.zip" Meta*
- cd ~
deploy:
  provider: releases
  api_key:
    secure: JsrCjD9M6FPnvKbDvlY62uvBStGsiSwgC90EuJr01288GNQPsp8eHOjZn6isBg+LCp8eqAvQOa7hQJbXG2RSZAw66Mvf1xjz7CEjzLRig1GC8do/t6qzRSaUg4YxDLn9lOY3OZ7GUdNQcDsgg5sVpVecx7B9ve3ZleH0l0kT1OHDN33v3a/oBHWsm/e06cXRw5M4L49ovE3V6fNCJDgaqtUn+0/pT002bMw+nobJaYE1KVZstfFohY/Sy4rGiXFT9dChwXzSp+hZf2Imcm15t4t2EFxObozWubZin5njXmRDr66xj1skkvhaxRxYGs9c8K75ySB+nK8pMk8dGoCquzvHuwoIxSYHTfJCwug3Es2LbTwQXNnfnjvXiqQU5886NvdzZiU17aYSg+fTEoAaFoCsMK12xx+Y3DxvCuunJSIz+Ke2CnEJm2yH7UAyaTWPbkZPfTcauFwegModuV2CW5yemXIMddmDunoY1EMIp6qURjYZS/HqYGX9fsKHYyyzm+dBG9dF5beMMpuxJ7C/e+GZa4z/BQ6bcRwUP8PIaqZXrm5UZ4l4PvJlLtetbV1FVLNl8StrWffsWRcZtLtMgAHYswmL93RafjlMI6HhWzQxmY+U3TS94/bgRuy3bIb/+GnCBtXi8y749zu1S+r5UApuCyyhOfwonhpfbie1m8M=
  file_glob: true
  skip_cleanup: true
  file: "mt-*.zip"
  on:
    repo: EA31337/FX-MT-VM
    tags: true
after_deploy:
- echo "done."
