# yamllint disable rule:line-length
---
dist: xenial
language: generic
services:
  - docker
env:
  global:
    - |
      PATH=${PATH//:\.\/node_modules\/\.bin/} # Workaround for Travis issue #4862
      CWD="$TRAVIS_BUILD_DIR"
      DOCKER_ARG="-e OPT_TRACE=$OPT_TRACE"
  matrix:
    - CMD="docker-compose run RunHelp; scripts/eval.sh help; scripts/run_backtest.sh -?"
    - CMD="docker-compose run $DOCKER_ARG BtDataGet_N0"
    - CMD="docker-compose run $DOCKER_ARG DockerLargeFiles"

# Tests which suppose to be working in older versions only.
# - TEST_ARGS="-v -t -d 1000 -p EURUSD -m 1-12 -y 2015 -S 10 -b DS -D5 -e TestFXTHeader -M4.0.0.971 -R"
# - TEST_ARGS="-v -t -d 1000 -p EURUSD -m 1-12 -y 2015 -S 10 -b DS -D5 -e TestFXTHeader -M4.0.0.988 -R"
# - TEST_ARGS="-v -t -d 1000 -p EURUSD -m 1-12 -y 2015 -S 10 -b DS -D5 -e TestHSTHeader -M4.0.0.988 -R"
# - TEST_ARGS="-v -t -d 1000 -p EURUSD -m 1-12 -y 2015 -S 10 -b DS -D5 -e TestHSTHeader -R -M4.0.0.988"
# Tests which does not work.
# - TEST_ARGS="-v -t -M4x -d 1000 -p EURUSD -m 1-12 -y 2015 -S 10 -b DS -D5 -e TestTimeframes -T M1"
# - TEST_ARGS="-v -t -M4x -d 1000 -p EURUSD -m 1-12 -y 2015 -S 10 -b DS -D5 -e TestBands -T M1"
before_install:
  - ulimit -a && free -m
  - chmod 777 $HOME/.cache
install:
  - make docker-load
before_script:
  - docker --version && docker-compose --version
  - docker info
  - docker images
script:
  - set -e
  - echo $CMD
  - eval $CMD
after_script:
  - set +x
after_success:
after_failure:
  - bash -x "$CWD"/scripts/.vars.inc.sh
  - docker history -H --no-trunc $DOCKER_REPO
  - docker-compose logs
cache:
  apt: true
  pip: true
  directories:
    - /var/cache
    - /var/lib/docker
    - $HOME/.cache
    - $HOME/.docker
