environment:
  FILELOG: metaeditor.log
install:
- appveyor DownloadFile https://github.com/EA31337/MetaEditor/raw/master/metaeditor.exe
before_test:
- git submodule update --init
test_script:
- |-
  metaeditor /s /compile:tests /log:%FILELOG% || exit /b 0
  type %FILELOG%
  find "Result" %FILELOG% | findstr /R /C:"Result 0 error(s), 0 warning(s)" /V
  find "Result" %FILELOG% | findstr /R /C:"Result 0 error(s), 0 warning(s)" /V | findstr /R /C:"Result [1-9][0-9]* error(s), [1-9][0-9]* warning(s)" /V
build: off
platform: x86
