version: '3'
services:
# General tests.
  TestSyntaxVagrantfile:
    command: ruby -wc /opt/src/Vagrantfile
    image: ruby
    volumes:
    - .:/opt/src
  TestSyntaxBash:
    command: bash -c 'bash -n $$(find /opt/scripts -name "*.sh" -print)'
    image: bash
    volumes:
    - ./scripts:/opt/scripts
  TestSyntaxShellcheck:
    command: -e SC1004,SC1083,SC1090,SC1091,SC1117,SC2004,SC2005,SC2015,SC2027,SC2032,SC2033,SC2034,SC2035,SC2046,SC2068,SC2070,SC2071,SC2086,SC2091,SC2103,SC2116,SC2124,SC2128,SC2145,SC2154,SC2155,SC2162,SC2164,SC2166,SC2181,SC2188,SC2206,SC2221,SC2222,SC2230 /opt/scripts/eval.sh /opt/scripts/run_backtest.sh /opt/scripts/provision.sh /opt/scripts/.vars.inc.sh /opt/scripts/install_mt5.sh /opt/scripts/.aliases.inc.sh /opt/scripts/get_bt_data.sh /opt/scripts/get_gh_asset.sh /opt/scripts/push_repo.sh /opt/scripts/run_terminal.sh /opt/scripts/.funcs.inc.sh /opt/scripts/dl_ea.sh /opt/scripts/clone_repo.sh /opt/scripts/.funcs.cmds.inc.sh /opt/scripts/install_mt4.sh /opt/scripts/install_mt4x.sh
    image: koalaman/shellcheck
    volumes:
    - ./scripts:/opt/scripts

# Shell script tests.
  RunHelp:
    command: help
    image: ea31337/ea-tester
    volumes:
    - ./scripts:/opt/scripts
  RunInstallMt4:
    command: install_mt 4
    image: ea31337/ea-tester:dev
    volumes:
    - ./scripts:/opt/scripts
  RunInstallMt4x:
    command: install_mt 4x
    image: ea31337/ea-tester:dev
    volumes:
    - ./scripts:/opt/scripts
  RunInstallMt5:
    command: install_mt 5
    image: ea31337/ea-tester:dev
    volumes:
    - ./scripts:/opt/scripts
  RunCompileMql:
    command: compile /opt/tests mql.log
    image: ea31337/ea-tester
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests:rw
    environment:
      OPT_TRACE: $OPT_TRACE

# Docker image tests
  DockerLargeFiles:
    entrypoint: /lib64/ld-linux-x86-64.so.2
    command: /usr/bin/find / -xdev -type f -size +10M -ls
    user: root
    image: ea31337/ea-tester
    volumes:
    - ./scripts:/opt/scripts

# MQL EA tests.
  TestBands:
    command: for tf in M15 M30; do run_backtest -e TestBands -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
      RUN_ON_START: clean_ea
  TestEnvelopes:
    command: for tf in M15 M30; do run_backtest -e TestEnvelopes -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
      RUN_ON_START: clean_ea
  TestFXTHeader:
    command: for tf in M1 M30; do run_backtest -e TestFXTHeader -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
      RUN_ON_START: clean_ea
  TestHSTHeader:
    command: for tf in M1 M30; do run_backtest -e TestHSTHeader -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
      RUN_ON_START: clean_ea
  TestLeverage:
    command: run_backtest -e TestLeverage
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
  TestLotstep4:
    command: run_backtest -e TestLotstep -D4 -l 0.1
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
  TestLotstep5:
    command: run_backtest -e TestLotstep -D5 -l 0.01
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
  TestMargin:
    command: run_backtest -e TestMargin
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
  TestModellingQuality:
    command: for tf in M1 M5 M15 M30; do run_backtest -e TestModellingQuality -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
      RUN_ON_START: clean_ea
  TestSpread:
    command: run_backtest -e TestSpread
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
  TestSymbolsRaw:
    command: run_backtest -e TestSymbolsRaw
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
  TestSymbolsSel:
    command: run_backtest -e TestSymbolsSel
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
  TestSymgroupsRaw:
    command: run_backtest -e TestSymgroupsRaw
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
  TestTicksRaw:
    command: run_backtest -e TestTicksRaw
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
  TestTimeframes:
    command: for tf in M15 M30; do run_backtest -e TestTimeframes -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
    environment:
      BT_DAYS: 10-12
      BT_MONTHS: 1
      RUN_ON_START: clean_ea

# MQL Scripts.
  ScriptPrintPaths:
    command: run_backtest -s PrintPaths
    image: ea31337/ea-tester:dev
    volumes:
    - ./scripts:/opt/scripts
    - ./tests:/opt/tests
    - ./conf:/opt/conf
