version: '3'
services:
# General tests.
  TestSyntaxVagrantfile:
    command: ruby -wc /opt/src/Vagrantfile
    image: ruby
    volumes:
    - ./:/opt/src
  TestSyntaxBash:
    command: bash -c 'bash -n $$(find /opt/src -name "*.sh" -print)'
    image: bash
    volumes:
    - ./:/opt/src
  TestSyntaxShellcheck:
    command: -e SC1004,SC1083,SC1090,SC1091,SC1117,SC2004,SC2005,SC2015,SC2027,SC2032,SC2033,SC2034,SC2035,SC2046,SC2068,SC2070,SC2071,SC2086,SC2091,SC2103,SC2116,SC2124,SC2128,SC2145,SC2154,SC2155,SC2162,SC2164,SC2166,SC2181,SC2188,SC2206,SC2221,SC2222,SC2230 /opt/src/scripts/eval.sh /opt/src/scripts/run_backtest.sh /opt/src/scripts/provision.sh /opt/src/scripts/.vars.inc.sh /opt/src/scripts/install_mt5.sh /opt/src/scripts/.aliases.inc.sh /opt/src/scripts/get_bt_data.sh /opt/src/scripts/get_gh_asset.sh /opt/src/scripts/push_repo.sh /opt/src/scripts/run_terminal.sh /opt/src/scripts/.funcs.inc.sh /opt/src/scripts/dl_ea.sh /opt/src/scripts/clone_repo.sh /opt/src/scripts/.funcs.cmds.inc.sh /opt/src/scripts/install_mt4.sh /opt/src/scripts/install_mt4x.sh
    image: koalaman/shellcheck
    volumes:
    - ./:/opt/src

# Shell script tests.
  RunHelp:
    command: help
    image: ea31337/ea-tester:dev
    tty: true
  RunInstallMt4:
    command: install_mt 4
    image: ea31337/ea-tester:dev
    tty: true
  RunInstallMt4x:
    command: install_mt 4x
    image: ea31337/ea-tester:dev
    tty: true
  RunInstallMt5:
    command: install_mt 5
    image: ea31337/ea-tester:dev
    tty: true

# Docker image tests
  DockerLargeFiles:
    entrypoint: /lib64/ld-linux-x86-64.so.2
    command: /usr/bin/find / -xdev -type f -size +10M -ls
    user: root
    image: ea31337/ea-tester:dev
    tty: true

# MQL EA tests.
  TestBands:
    command: for tf in M15 M30; do run_backtest -e TestBands -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
#   - ../EA-Tester/scripts:/opt/scripts
    tty: true
    environment:
      BT_MONTHS: 1
  TestEnvelopes:
    command: for tf in M15 M30; do run_backtest -e TestEnvelopes -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestFXTHeader:
    command: run_backtest -e TestFXTHeader
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestHSTHeader:
    command: run_backtest -e TestHSTHeader
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestLotstep4:
    command: run_backtest -e TestLotstep -D 4
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestLotstep5:
    command: run_backtest -e TestLotstep -D 5
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestMargin:
    command: run_backtest -e TestMargin
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestModellingQuality:
    command: for tf in M1 M5 M15 M30; do run_backtest -e TestModellingQuality -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestSpread:
    command: run_backtest -e TestSpread
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestSymbolsRaw:
    command: run_backtest -e TestSymbolsRaw
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestSymbolsSel:
    command: run_backtest -e TestSymbolsSel
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestSymgroupsRaw:
    command: run_backtest -e TestSymgroupsRaw
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestTicksRaw:
    command: run_backtest -e TestTicksRaw
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1
  TestTimeframes:
    command: for tf in M15 M30; do run_backtest -e TestTimeframes -T $$tf; done
    image: ea31337/ea-tester:EURUSD-2018-DS
    volumes:
    - ./tests:/opt/src
    tty: true
    environment:
      BT_MONTHS: 1

# MQL Scripts.
  PrintPaths:
    command: run_backtest -e PrintPaths
    image: ea31337/ea-tester:dev
    volumes:
    - ./tests/scripts:/opt/src
    tty: true
