# yamllint disable rule:line-length
---
version: '3'
services:
  # General tests.
  TestSyntaxVagrantfile:
    command: ruby -wc /opt/src/Vagrantfile
    image: ruby
    volumes:
      - .:/opt/src
  TestSyntaxBash:
    command: bash -c 'bash -n $$(find /opt/scripts -name "*.sh" -print)'
    image: bash
    volumes:
      - ./scripts:/opt/scripts
  TestSyntaxShellcheck:
    command: -e SC1004,SC1083,SC1090,SC1091,SC1117,SC2004,SC2005,SC2015,SC2027,SC2032,SC2033,SC2034,SC2035,SC2046,SC2068,SC2070,SC2071,SC2086,SC2091,SC2103,SC2116,SC2124,SC2128,SC2145,SC2154,SC2155,SC2162,SC2164,SC2166,SC2181,SC2188,SC2206,SC2221,SC2222,SC2230,SC2294 /opt/scripts/eval.sh /opt/scripts/run_backtest.sh /opt/scripts/provision.sh /opt/scripts/.vars.inc.sh /opt/scripts/install_mt5.sh /opt/scripts/.aliases.inc.sh /opt/scripts/bt_data_get.sh /opt/scripts/get_gh_asset.sh /opt/scripts/push_repo.sh /opt/scripts/run_terminal.sh /opt/scripts/.funcs.inc.sh /opt/scripts/dl_ea.sh /opt/scripts/clone_repo.sh /opt/scripts/.funcs.cmds.inc.sh /opt/scripts/install_mt4.sh /opt/scripts/install_mt4x.sh
    image: koalaman/shellcheck
    volumes:
      - ./scripts:/opt/scripts
  TestSyntaxPython:
    entrypoint: /bin/bash
    command: -c 'find /opt/scripts/py -name "*.py" -exec python3 -B -m py_compile {} +'
    image: ea31337/ea-tester
    volumes:
      - ./scripts:/opt/scripts:rw
  TestSyntax:
    command: "true"
    image: bash
    depends_on:
      - TestSyntaxBash
      - TestSyntaxPython
      - TestSyntaxShellcheck
      - TestSyntaxVagrantfile

  # Shell script tests.
  RunHelp:
    command: help
    image: ea31337/ea-tester
    volumes:
      - ./scripts:/opt/scripts
  RunInstallMt4:
    command: install_mt 4
    image: ea31337/ea-tester:dev
    volumes:
      - ./scripts:/opt/scripts
  RunInstallMt4x:
    command: install_mt 4x
    image: ea31337/ea-tester:dev
    volumes:
      - ./scripts:/opt/scripts
  RunInstallMt5:
    command: install_mt 5
    image: ea31337/ea-tester:dev
    volumes:
      - ./scripts:/opt/scripts
  RunCompileMql:
    command: compile /opt/tests mql.log
    image: ea31337/ea-tester
    volumes:
      - ./scripts:/opt/scripts
      - ./tests:/opt/tests:rw
    environment:
      OPT_TRACE: $OPT_TRACE
  BtDataGet_EURUSD_2018:
    command: bt_data_get EURUSD 2018 DS
    image: ea31337/ea-tester
    volumes:
      - ./scripts:/opt/scripts
    environment:
      OPT_TRACE: $OPT_TRACE
  BtDataGet_EURUSD_2019:
    command: bt_data_get EURUSD 2019 DS
    image: ea31337/ea-tester
    volumes:
      - ./scripts:/opt/scripts
    environment:
      OPT_TRACE: $OPT_TRACE
  BtDataGet_N0:
    command: bt_data_get XXXYYY 2010 N0 M1
    image: ea31337/ea-tester
    volumes:
      - ./scripts:/opt/scripts
    environment:
      OPT_TRACE: $OPT_TRACE

  # Docker image tests
  DockerLargeFiles:
    entrypoint: /lib64/ld-linux-x86-64.so.2
    command: /usr/bin/find / -xdev -type f -size +10M -ls
    user: root
    image: ea31337/ea-tester
    volumes:
      - ./scripts:/opt/scripts
  Shell:
    entrypoint: /bin/bash
    image: ea31337/ea-tester
    volumes:
      - ./scripts:/opt/scripts
      - ./tests:/opt/tests
      - ./conf:/opt/conf
