# A file containing a list of collections to be installed.
# Usage:
# ansible-galaxy install -r requirements.yml
---
roles:
  - name: ea31337.mt_runner
    scm: git
    src: https://github.com/EA31337/ansible-role-mt-runner.git
    version: dev
