---
name: Check

on:
  pull_request:
  push:

jobs:
  Pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Installs shfmt
        run: >
          sudo install /dev/stdin /usr/local/bin/shfmt
          < <(curl -L "$SHFMT_URL")
        env:
          SHFMT_URL: https://github.com/mvdan/sh/releases/download/v3.1.1/shfmt_v3.1.1_linux_amd64
      - uses: actions/setup-python@v1
      - uses: pre-commit/action@v2.0.0
