---
name: Lint
on:
  - pull_request
  - push
jobs:
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: YAML check (yamllint)
        uses: ibiqlik/action-yamllint@master
        with:
          strict: true
  Markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: .
          config_file: ".markdownlint.yaml"
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Shell Check
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true
          sh_checker_shfmt_disable: true
  MQL:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: DoozyX/clang-format-lint-action@v0.5
        with:
          extensions: 'h'
  Syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run RunCompileMql
        run: docker-compose run RunCompileMql
      - name: Run TestSyntaxBash
        run: docker-compose run TestSyntaxBash
      - name: Run TestSyntaxShellcheck
        run: docker-compose run TestSyntaxShellcheck
      - name: Run TestSyntaxVagrantfile
        run: docker-compose run TestSyntaxVagrantfile
