# yamllint disable rule:line-length
---
name: Lint
on:
  - pull_request
  - push
jobs:
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: YAML check (yamllint)
        uses: ibiqlik/action-yamllint@master
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - name: Shell Check
        uses: bewuethr/shellcheck-action@v2
        env:
          SHELLCHECK_OPTS: >
            -e SC1004,SC1083,SC1090,SC1091,SC1117,SC2004,SC2005,SC2015,SC2027
            -e SC2032,SC2033,SC2034,SC2035,SC2046,SC2068,SC2070,SC2071,SC2086
            -e SC2091,SC2103,SC2116,SC2124,SC2128,SC2145,SC2154,SC2155,SC2162
            -e SC2164,SC2166,SC2181,SC2188,SC2206,SC2221,SC2222,SC2230
