---
name: Tests-Shell

on:
  - pull_request
  - push

jobs:
  Test-Provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: id
      # - name: Adds ubuntu user
      # run: useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo ubuntu
      - name: Runs provisioning script
        run: ./scripts/provision.sh
  Test-Scripts:
    runs-on: ubuntu-latest
    container:
      image: ea31337/ea-tester:dev
      volumes:
        - ${{ github.workspace }}/scripts/tests:/opt/scripts
    steps:
      - run: pwd
      - run: tree
      - run: id
      - run: ls -la /opt/scripts
      # @fixme
      # - name: Test .vars.inc.sh file
      # # working-directory: /opt/scripts/tests
      # run: /opt/scripts/tests/test_vars.sh
