---
name: Tests-Shell

on:
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/tests-shell.yml'
  push:
    paths:
      - '**/*.sh'
      - '.github/workflows/tests-shell.yml'

jobs:
  Tests-Scripts:
    runs-on: ubuntu-latest
    container:
      image: ea31337/ea-tester:dev
    steps:
      - uses: actions/checkout@v2
      - run: ./test_aliases.sh
        working-directory: scripts/tests
      - run: ./test_backtest.sh
        working-directory: scripts/tests
      - run: ./test_bt_data_gen.sh
        working-directory: scripts/tests
      - run: ./test_cmds.sh
        working-directory: scripts/tests
      - run: ./test_eval.sh
        working-directory: scripts/tests
      - run: ./test_vars.sh
        working-directory: scripts/tests
