---
name: Tests-MQL

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**/docker-compose.yml'
      - '**/*.mq?'
      - '.github/workflows/tests-mql.yml'
  push:
    paths:
      - '**/docker-compose.yml'
      - '**/*.mq?'
      - '.github/workflows/tests-mql.yml'

jobs:
  Tests-MT4:
    defaults:
      run:
        shell: bash
        working-directory: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - ScriptDummy
          - ScriptPrintPaths
          - TestBands
          - TestEnvelopes
          - TestFXTHeader
          - TestHSTHeader
          - TestLotstep4
          - TestModellingQuality
          - TestTimeframes
    steps:
      - uses: actions/checkout@v2
      - name: Check dependencies
        if: github.actor == 'nektos/act'
        run: >
          apt-get update
          && apt-get -qq install python-pip
          && pip install docker-compose
      - name: Run ${{ matrix.test }}
        run: docker-compose run ${{ matrix.test }}
  Tests-MT4-Ignored:
    defaults:
      run:
        shell: bash
        working-directory: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - ScriptDummy
          - TestLeverage
          - TestLotstep5
          - TestMargin
          - TestSpread
          - TestSymbolsRaw
          - TestSymbolsRaw
          - TestSymgroupsRaw
          - TestTicksRaw
    steps:
      - uses: actions/checkout@v2
      - name: Check dependencies
        if: github.actor == 'nektos/act'
        run: >
          apt-get update
          && apt-get -qq install python-pip
          && pip install docker-compose
      - name: Run ${{ matrix.test }}
        run: docker-compose run ${{ matrix.test }} || true
