---
name: Tests-Shell

on:
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/tests-shell.yml'
  push:
    paths:
      - '**/*.sh'
      - '.github/workflows/tests-shell.yml'

jobs:
  Tests-Scripts:
    runs-on: ubuntu-latest
    container:
      image: ea31337/ea-tester:dev
    steps:
      - uses: actions/checkout@v2
      - name: Prepare folder
        run: ln -fsv scripts /opt/scripts
      - name: Run test scripts
        working-directory: scripts/tests
        run: find . -name "*.sh" -print -exec {} ";"
