---
name: Tests-Shell

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - '**/*.sh'
      - '.github/workflows/tests-shell.yml'
  push:
    paths:
      - '**/*.sh'
      - '.github/workflows/tests-shell.yml'

jobs:
  Test-Scripts:
    defaults:
      run:
        shell: bash
        working-directory: scripts/tests
    runs-on: ubuntu-latest
    container:
      env:
        OPT_TRACE: ${{ runner.debug }}
        OPT_VERBOSE: true
      image: ea31337/ea-tester:dev
      options: --user root
      volumes:
        - ${{ github.workspace }}/scripts/tests:/opt/scripts
    strategy:
      matrix:
        test:
          - ./test_aliases.sh
          - ./test_backtest.sh
          - ./test_bt_data_gen.sh
          - ./test_cmds.sh
          - ./test_compile.sh
          - ./test_eval.sh
          - ./test_vars.sh
    steps:
      - uses: actions/checkout@v3
        env:
          GIT_CEILING_DIRECTORIES: /__w
      - run: ${{ matrix.test }}
