---
name: Tests-Shell

on:
  - pull_request
  - push

jobs:
  Tests-Scripts:
    runs-on: ubuntu-latest
    container:
      image: ea31337/ea-tester:dev
    steps:
      - uses: actions/checkout@v2
      - run: rm -fr /opt/scripts
      - run: ln -fs scripts /opt/scripts
      - name: Test .vars.inc.sh file
        working-directory: scripts/tests
        run: ./test_vars.sh
